apiVersion: v1
kind: Secret
metadata:
  name: finance-api-secrets
  namespace: finance
type: Opaque
data:
  ConnectionStrings__Default: "SG9zdD1maW5hbmNlLXBvc3RncmVzLnNlcnZpY2U7RGF0YWJhc2U9ZmluYW5jZTtVc2VybmFtZT1maW5hbmNlO1Bhc3N3b3JkPWZpbmFuY2U="
  Keycloak__ClientSecret: "ZmluYW5jZS1hcGktc2VjcmV0"
  Postgres__Password: "ZmluYW5jZQ=="
